repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: check-added-large-files
        args: [--maxkb=5000]
-   repo: https://github.com/psf/black
    rev: 23.10.0
    hooks:
    -   id: black
        args: [--line-length=79]
        types: [python]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: [--line-length=79, --profile=black]
        types: [python]
